name: gsee37
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - brotli-python=1.0.9=py37hd23a5d3_7
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cftime=1.6.2=py37hc105733_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - curl=8.17.0=h4e3cde8_1
  - dataclasses=0.8=pyhc8e2a94_3
  - ephem=4.1.3=py37h540881e_4
  - gsee=0.3.1=py37h516909a_0
  - h5py=3.7.0=nompi_py37hf1ce037_101
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=78.1=h33c6efd_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py37h89c1867_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libcurl=8.17.0=h4e3cde8_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.9.0=20_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.8.1=nompi_h21705cb_104
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libsqlite=3.51.1=hf4e2dac_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.39.1=py37h0761922_0
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.6.1=nompi_py37hb61e06c_100
  - numba=0.56.3=py37hf081915_0
  - numpy=1.21.6=py37h976b520_0
  - openssl=3.6.0=h26f9b46_0
  - pandas=0.24.0=py37he6710b0_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - pvlib-python=0.9.1=pyhd8ed1ab_0
  - pyephem=3.7.6.0=py37h14c3975_1000
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.7=4_cp37m
  - pytz=2024.2=pyhd8ed1ab_0
  - readline=8.3=h853b02a_0
  - requests=2.32.2=pyhd8ed1ab_0
  - scipy=1.7.3=py37hf2a6cf1_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.51.1=h04a0ce9_1
  - statsmodels=0.12.2=py37hb1e94ed_0
  - tk=8.6.13=noxft_ha0e22de_103
  - typing_extensions=4.7.1=pyha770c72_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xarray=0.11.0=py37_1000
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/norman/miniconda3/envs/gsee37
